### PR TITLE
Implement a Linear & NonLinear UndoManager

### PR DESCRIPTION
**Pull request by JordanMartinez**

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Truth be told, this approach is more like an UndoManager for a Single use case (LinearUndoManager) and an "wrapper" UndoManager (NonLinearUndoManager) designed to be shared by multiple objects, with each object having its own ChangeQueue. However, it's not something that would work for a directed acyclic graph. 

Let's use RichTextFX as an example. Let's say there are two areas whose content starts with `text` as its initial text. Then, the user inserts `someText` into one area, thus making it's next `undo()` call an action that will remove that text. Third, the user deletes the content's text in the second area. Fourth, the user undoes the first area's insertion (removes `someText`). This fourth step would throw an Exception of some sort because it cannot delete text that is no longer there.

**Comment by TomasMikula** [comment]
Exactly.

**Comment by JordanMartinez** [comment]
Still, it was a good mental exercise for me. :-)

**Comment by TomasMikula** [comment]
At least you got something out of it, heh :D

**Comment by JordanMartinez** [comment]
> At least you got something out of it, heh :D

Well I'm never going to learn and grow if I don't try to do something challenging :D "Failing" is learning, not failing.

**Comment by TomasMikula** [comment]
That's the right attitude :+1:

**Pull request closed without merging**
